os:
  - linux
  - osx
dist: trusty
language: perl6
perl6:
  - latest

install:
  - myfont="3rdparty/NotoSans-Bold.ttf"
  - "fc-scan -f 'Charset: %{charset}' '3rdparty/NotoSans-Bold.ttf'"
  - rakudobrew build zef
  - zef install --depsonly --/test .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/

sudo: false
